name: pull-request-info-action
description: |
  Github Action which returns Pull Request Information based on commit_sha.
  This is for scenarios when you need that information on main branch after PR is merged
author: Dusan Plavak (ddeath)

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  github-token:
    description: 'The repository token, i.e. secrets.GITHUB_TOKEN'
    required: true
  commit_sha:
    description: Commit Sha for which you want to lookup PR information. If not provided github.sha will be used
    required: false

# Define your outputs here.
outputs:
  labels:
    description: List of labels on PR
  pullRequestBranchName:
    description: Name of the from which PR was open

runs:
  using: node20
  main: dist/index.js
