name: pull-request-info-action
description: |
  Github Action which returns Pull Request Information based on commit_sha.
  This is for scenarios when you need that information on main branch after PR is merged
author: Dusan Plavak (ddeath)

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  github_token:
    description: 'The repository token, i.e. secrets.GITHUB_TOKEN'
    required: true
  commit_sha:
    description: Commit Sha for which you want to lookup PR information. If not provided github.sha will be used
    required: false
  only_merged:
    description: If true, discards all PRs which are not merged
    default: 'true'
  target_branch:
    description: This will keep only PRs which were / will be merged to targetBranch
    default: 'main'
  fail_on_missing_pr:
    description: Action will fail if no associated PRs which also match filtering option is found
    default: 'true'

# Define your outputs here.
outputs:
  pullRequests:
    description: |
      List of PullRequests referencing specified commit and filter.
      Response has format of Github Api Rest response from this call:
      https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#list-pull-requests-associated-with-a-commit

runs:
  using: node20
  main: dist/index.js
